<?xml version="1.0" encoding="utf-8"?><Database Name="20131011110029" Class="LojaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=valera;Initial Catalog=20131011110029;Integrated Security=True" SettingsObjectName="Dados.Properties.Settings" SettingsPropertyName="_20131011110029ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Fabricante" Member="Fabricantes">
    <Type Name="Fabricante">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Fabricante_Veiculo" Member="Veiculos" ThisKey="Id" OtherKey="IdFabricante" Type="Veiculo" />
    </Type>
  </Table>
  <Table Name="dbo.Veiculo" Member="Veiculos">
    <Type Name="Veiculo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Modelo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Ano" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdFabricante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DataCompra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValorCompra" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="PrecoVenda" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DataVenda" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ValorVenda" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="Fabricante_Veiculo" Member="Fabricante" ThisKey="IdFabricante" OtherKey="Id" Type="Fabricante" IsForeignKey="true" />
    </Type>
  </Table>
</Database>